-- Chạy toàn bộ file này một lần trong Supabase -> SQL Editor.
-- Bot backend dùng SUPABASE_SECRET_KEY (khuyên dùng) hoặc legacy service_role key.

create table if not exists public.bot_users (
    telegram_id bigint primary key,
    username text,
    first_name text,
    last_name text,
    language_code text,
    created_at timestamptz not null default now(),
    last_active_at timestamptz not null default now()
);

create table if not exists public.bot_user_state (
    telegram_user_id bigint primary key references public.bot_users(telegram_id) on delete cascade,
    state jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.bot_files (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint references public.bot_users(telegram_id) on delete set null,
    storage_chat_id bigint not null,
    storage_message_id bigint not null,
    telegram_file_id text,
    telegram_file_unique_id text,
    file_name text,
    mime_type text,
    file_type text not null,
    file_size bigint,
    source_chat_id bigint,
    source_message_id bigint,
    created_at timestamptz not null default now(),
    unique (storage_chat_id, storage_message_id)
);

create index if not exists idx_bot_files_user_created
    on public.bot_files (telegram_user_id, created_at desc);

create table if not exists public.bot_updates (
    update_id bigint primary key,
    status text not null default 'processing' check (status in ('processing', 'done', 'failed')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Backend secret/service_role key bypasses RLS. Keep public clients locked out.
alter table public.bot_users enable row level security;
alter table public.bot_user_state enable row level security;
alter table public.bot_files enable row level security;
alter table public.bot_updates enable row level security;

grant all on table public.bot_users to service_role;
grant all on table public.bot_user_state to service_role;
grant all on table public.bot_files to service_role;
grant all on table public.bot_updates to service_role;
grant usage, select on all sequences in schema public to service_role;
